// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	Location
	AddressBook
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number" json:"number,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type Location struct {
	Longitude float32 `protobuf:"fixed32,1,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type AddressBook struct {
	Imei   string    `protobuf:"bytes,1,opt,name=imei" json:"imei,omitempty"`
	Number string    `protobuf:"bytes,2,opt,name=number" json:"number,omitempty"`
	Cc     string    `protobuf:"bytes,3,opt,name=cc" json:"cc,omitempty"`
	Ip     string    `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	Ts     int64     `protobuf:"varint,5,opt,name=ts" json:"ts,omitempty"`
	Loc    *Location `protobuf:"bytes,6,opt,name=loc" json:"loc,omitempty"`
	People []*Person `protobuf:"bytes,7,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressBook) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *AddressBook) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *AddressBook) GetCc() string {
	if m != nil {
		return m.Cc
	}
	return ""
}

func (m *AddressBook) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddressBook) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *AddressBook) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "pb.Person")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*AddressBook)(nil), "pb.AddressBook")
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xba, 0xc6, 0xdd, 0x59, 0x11, 0x9c, 0x83, 0x04, 0x11, 0x29, 0x3d, 0xf5, 0xd4,
	0xc3, 0xea, 0x0b, 0x28, 0x1e, 0x3d, 0x48, 0xde, 0xa0, 0x49, 0x83, 0x84, 0x6d, 0x33, 0xa1, 0xc9,
	0x3e, 0x96, 0xef, 0x28, 0x49, 0x76, 0xf5, 0xe4, 0x6d, 0xbe, 0xff, 0x4f, 0xe0, 0x9b, 0x81, 0xbb,
	0x71, 0x9a, 0x56, 0x1b, 0xa3, 0x26, 0x3a, 0x0e, 0x61, 0xa5, 0x44, 0xc8, 0x83, 0xee, 0x5e, 0x40,
	0x7c, 0xda, 0x35, 0x92, 0x47, 0x84, 0x8d, 0x1f, 0x17, 0x2b, 0x59, 0xcb, 0xfa, 0x9d, 0x2a, 0x33,
	0xde, 0x83, 0xf0, 0xa7, 0x45, 0xdb, 0x55, 0xf2, 0x92, 0x9e, 0xa9, 0x7b, 0x87, 0xed, 0x07, 0x99,
	0x31, 0x39, 0xf2, 0xf8, 0x08, 0xbb, 0x99, 0xfc, 0x97, 0x4b, 0xa7, 0xa9, 0x7e, 0xe6, 0xea, 0x2f,
	0xc0, 0x07, 0xd8, 0xce, 0x63, 0xaa, 0x25, 0x2f, 0xe5, 0x2f, 0x77, 0xdf, 0x0c, 0xf6, 0xaf, 0xd5,
	0xea, 0x8d, 0xe8, 0x98, 0x0d, 0xdc, 0x62, 0xdd, 0xc5, 0x20, 0xcf, 0xff, 0x19, 0xe0, 0x2d, 0x70,
	0x63, 0x64, 0x53, 0x32, 0x6e, 0x4c, 0x66, 0x17, 0xe4, 0xa6, 0xb2, 0x0b, 0x99, 0x53, 0x94, 0x57,
	0x2d, 0xeb, 0x1b, 0xc5, 0x53, 0xc4, 0x27, 0x68, 0x66, 0x32, 0x52, 0xb4, 0xac, 0xdf, 0x1f, 0x6e,
	0x86, 0xa0, 0x87, 0xcb, 0x02, 0x2a, 0x17, 0xd8, 0x81, 0x08, 0x96, 0xc2, 0x6c, 0xe5, 0x75, 0xdb,
	0xf4, 0xfb, 0x03, 0xe4, 0x27, 0xf5, 0x32, 0xea, 0xdc, 0x68, 0x51, 0xce, 0xf6, 0xfc, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xa1, 0x38, 0x96, 0x23, 0x4b, 0x01, 0x00, 0x00,
}
